// <auto-generated />
using System;
using DVarr.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVarr.Data.Migrations
{
    [DbContext(typeof(DVarrDbContext))]
    [Migration("20260615061208_Phase7EpgCollation")]
    partial class Phase7EpgCollation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("DVarr.Data.Entities.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DetectedQuality")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpgChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameNorm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TvArchive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvArchiveDuration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LogicalKey");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceId", "StreamId");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("DVarr.Data.Entities.ChannelHealth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Alive")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BlackRatio")
                        .HasColumnType("REAL");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FingerprintHashesJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("FreezeRatio")
                        .HasColumnType("REAL");

                    b.Property<long?>("LastProbedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SilenceRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("ChannelHealth");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChannelLocked")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSeenSyncUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MonitoredLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceMetaJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartIsDateOnly")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TsdbEventId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.HasIndex("StartUtc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("DVarr.Data.Entities.EventSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ChannelLocked")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MonitoredLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NaturalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("StartIsDateOnly")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("NaturalKey")
                        .IsUnique();

                    b.ToTable("EventSessions");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IntervalS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("RunAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("StartedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("State", "RunAtUtc");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("DVarr.Data.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BadgeUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalLeagueId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcsUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastEventSyncUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleHorizonDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("DVarr.Data.Entities.LeagueChannelMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveFromUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActiveToUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeagueId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pinned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId", "Rank");

                    b.ToTable("LeagueChannelMaps");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DeliveredHa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromState")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToState")
                        .HasColumnType("TEXT");

                    b.Property<long>("TsUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TsUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Programme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("EpgChannelId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("EpgUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StopUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpgUid");

                    b.HasIndex("SourceId", "EpgChannelId", "StartUtc");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("DVarr.Data.Entities.ProviderSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedOutputFormats")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EpgOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpgUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpDateUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Healthy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HttpsPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastAuthAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStreams")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProviderActiveCons")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProviderMaxConns")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Recording", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesWritten")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConflictPolicy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DualCapture")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FfmpegPid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GapsJson")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastContentOkUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastFrameUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchQuery")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostPadS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrePadS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolutionSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentDir")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StartUtc");

                    b.HasIndex("State");

                    b.HasIndex("EventId", "State");

                    b.ToTable("Recordings");
                });

            modelBuilder.Entity("DVarr.Data.Entities.RecordingFallback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId", "Rank");

                    b.HasIndex("RecordingId", "SourceId");

                    b.ToTable("RecordingFallbacks");
                });

            modelBuilder.Entity("DVarr.Data.Entities.RecordingSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentVerdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seq")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Suspect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecordingId", "Capture", "Seq");

                    b.ToTable("RecordingSegments");
                });

            modelBuilder.Entity("DVarr.Data.Entities.ScheduleTick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Conflicts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Finalized")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Missed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordingsExamined")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resumed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Started")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TickUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TickUtc");

                    b.ToTable("ScheduleTicks");
                });

            modelBuilder.Entity("DVarr.Data.Entities.SecretEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Secrets");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("DVarr.Data.Entities.SourceLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirstSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InternalEventId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ProviderEventId");

                    b.ToTable("SourceLinks");
                });

            modelBuilder.Entity("DVarr.Data.Entities.TunerLease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AcquiredAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesWritten")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeadlineUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastHeartbeatUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Pid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecordingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "State");

                    b.ToTable("TunerLeases");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Channel", b =>
                {
                    b.HasOne("DVarr.Data.Entities.ProviderSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Event", b =>
                {
                    b.HasOne("DVarr.Data.Entities.League", "League")
                        .WithMany("Events")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("DVarr.Data.Entities.EventSession", b =>
                {
                    b.HasOne("DVarr.Data.Entities.Event", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("DVarr.Data.Entities.LeagueChannelMap", b =>
                {
                    b.HasOne("DVarr.Data.Entities.League", "League")
                        .WithMany("ChannelMaps")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("DVarr.Data.Entities.RecordingFallback", b =>
                {
                    b.HasOne("DVarr.Data.Entities.Recording", "Recording")
                        .WithMany("Fallbacks")
                        .HasForeignKey("RecordingId", "SourceId")
                        .HasPrincipalKey("Id", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("DVarr.Data.Entities.RecordingSegment", b =>
                {
                    b.HasOne("DVarr.Data.Entities.Recording", null)
                        .WithMany("Segments")
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DVarr.Data.Entities.TunerLease", b =>
                {
                    b.HasOne("DVarr.Data.Entities.ProviderSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Event", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DVarr.Data.Entities.League", b =>
                {
                    b.Navigation("ChannelMaps");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("DVarr.Data.Entities.Recording", b =>
                {
                    b.Navigation("Fallbacks");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
